# Generated by Django 3.2.9 on 2022-03-14 12:10

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=1, verbose_name='user age'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='content_choice',
            field=models.TextField(blank=True, verbose_name='User content-choices'),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, verbose_name='User facebook_link'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.TextField(blank=True, verbose_name='User full name'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=255, verbose_name='User gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, max_length=255, verbose_name='User language'),
        ),
        migrations.AddField(
            model_name='user',
            name='linked_in',
            field=models.CharField(blank=True, max_length=255, verbose_name='User linked in link'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='User phone no'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_and_rename, verbose_name='user profile pic'),
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='user secondary  email'),
        ),
    ]
