# Generated by Django 3.2.9 on 2022-03-16 14:09

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='content_choice',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linked_in',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='secondary_email',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=20, verbose_name='user country name')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_and_rename, verbose_name='user profile pic')),
                ('secondary_email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='user secondary  email')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='User phone no')),
                ('content_choice', models.TextField(blank=True, verbose_name='User content-choices')),
                ('gender', models.CharField(blank=True, max_length=255, verbose_name='User gender')),
                ('facebook', models.CharField(blank=True, max_length=255, verbose_name='User facebook_link')),
                ('linked_in', models.CharField(blank=True, max_length=255, verbose_name='User linked in link')),
                ('full_name', models.TextField(blank=True, verbose_name='User full name')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='user age')),
                ('language', models.CharField(blank=True, max_length=255, verbose_name='User language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auth User')),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfiles',
            },
        ),
    ]
