# Generated by Django 3.2.9 on 2022-03-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220316_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='user country name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User facebook_link'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.TextField(blank=True, null=True, verbose_name='User full name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='linked_in',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User linked in link'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User phone no'),
        ),
    ]
