# Generated by Django 3.2.9 on 2022-03-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220321_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pro',
            field=models.BooleanField(default=False, verbose_name='User is pro or not'),
        ),
        migrations.AddField(
            model_name='user',
            name='pro_expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Subscription expiry date'),
        ),
    ]
