# Generated by Django 3.2.9 on 2022-04-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='free_expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='free expiry date'),
        ),
    ]
