# Generated by Django 3.2.9 on 2022-04-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_free_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_pro',
            field=models.BooleanField(default=True, verbose_name='User is pro or not'),
        ),
    ]
