# Generated by Django 3.2.9 on 2022-04-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_is_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_buy',
            field=models.IntegerField(blank=True, null=True, verbose_name='user has subscribed how many times'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_pro',
            field=models.BooleanField(default=False, verbose_name='User is pro or not'),
        ),
    ]
