# Generated by Django 3.2.9 on 2022-03-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='video upload'),
        ),
    ]
