# Generated by Django 3.2.9 on 2022-03-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_video_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='video upload'),
        ),
    ]
