# Generated by Django 3.2.9 on 2022-03-13 16:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_video_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='upload',
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=cloudinary.models.CloudinaryField(default=11, max_length=255),
            preserve_default=False,
        ),
    ]
