# Generated by Django 3.2.9 on 2022-03-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_auto_20220313_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='subscription expiry date')),
            ],
        ),
    ]
