# Generated by Django 3.2.9 on 2022-03-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_usersubcription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubcription',
            options={'verbose_name': 'UserSubcription', 'verbose_name_plural': 'UserSubcriptions'},
        ),
    ]
