# Generated by Django 3.2.9 on 2022-03-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_auto_20220320_1606'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSubcription',
            new_name='UserSubscription',
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'verbose_name': 'UserSubscription', 'verbose_name_plural': 'UserSubscriptions'},
        ),
    ]
