# Generated by Django 3.2.9 on 2022-03-20 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0010_auto_20220320_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='is_pro',
            field=models.BooleanField(default=False, verbose_name='user is pro or not'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='Auth User'),
            preserve_default=False,
        ),
    ]
