# Generated by Django 3.2.9 on 2022-03-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_auto_20220321_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_oid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Video oid'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_upload_media',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='video upload media'),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_video_link',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube video link'),
        ),
    ]
