# Generated by Django 3.2.9 on 2022-03-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0013_auto_20220321_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Subscription name'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Subscription price'),
        ),
    ]
