# Generated by Django 3.2.9 on 2022-03-31 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0014_auto_20220322_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(related_name='video_likes', to=settings.AUTH_USER_MODEL, verbose_name='video likes'),
        ),
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.ManyToManyField(related_name='video_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
