# Generated by Django 3.2.9 on 2022-03-31 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0015_auto_20220331_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='video',
            name='views',
        ),
        migrations.CreateModel(
            name='VideoLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeusers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('likevideo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likevideo', to='category.video')),
            ],
            options={
                'verbose_name': 'VideoLike',
                'verbose_name_plural': 'VideoLikes',
            },
        ),
    ]
