# Generated by Django 3.2.9 on 2022-03-31 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0016_auto_20220331_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolikes',
            name='likevideo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likevideos', to='category.video'),
        ),
    ]
