# Generated by Django 3.2.9 on 2022-03-31 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0018_alter_videolikes_likevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolikes',
            name='likeusers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='liked user id list'),
        ),
        migrations.AlterField(
            model_name='videolikes',
            name='likevideo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.video', verbose_name='video id'),
        ),
        migrations.CreateModel(
            name='SaveVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id')),
                ('video', models.ManyToManyField(to='category.Video', verbose_name='saved videos id list')),
            ],
            options={
                'verbose_name': 'SaveVideo',
                'verbose_name_plural': 'SaveVideos',
            },
        ),
    ]
