# Generated by Django 3.2.9 on 2022-04-01 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0020_auto_20220331_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolikes',
            name='likevideo',
            field=models.OneToOneField(default=11, on_delete=django.db.models.deletion.CASCADE, to='category.video', verbose_name='video id'),
            preserve_default=False,
        ),
    ]
