# Generated by Django 3.2.9 on 2022-04-02 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0021_alter_videolikes_likevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentShownVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id')),
                ('video', models.ManyToManyField(to='category.Video', verbose_name='saved videos id list')),
            ],
            options={
                'verbose_name': 'RecentShownVideo',
                'verbose_name_plural': 'RecentShownVideos',
            },
        ),
    ]
