# Generated by Django 3.2.9 on 2022-04-03 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0022_recentshownvideos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolikes',
            name='likeusers',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='liked user id list'),
        ),
        migrations.AlterField(
            model_name='videolikes',
            name='likevideo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.video', verbose_name='video id'),
        ),
    ]
