# Generated by Django 3.2.9 on 2022-04-04 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0023_auto_20220403_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolikes',
            name='likeusers',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='liked user id list'),
        ),
    ]
