# Generated by Django 3.2.9 on 2022-04-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0024_alter_videolikes_likeusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentshownvideos',
            name='video',
            field=models.ManyToManyField(blank=True, to='category.Video', verbose_name='saved videos id list'),
        ),
        migrations.AlterField(
            model_name='savevideos',
            name='video',
            field=models.ManyToManyField(blank=True, to='category.Video', verbose_name='saved videos id list'),
        ),
    ]
