# Generated by Django 3.2.9 on 2022-04-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0025_auto_20220404_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentshownvideos',
            name='video',
            field=models.ManyToManyField(blank=True, null=True, to='category.Video', verbose_name='saved videos id list'),
        ),
        migrations.AlterField(
            model_name='savevideos',
            name='video',
            field=models.ManyToManyField(blank=True, null=True, to='category.Video', verbose_name='saved videos id list'),
        ),
    ]
