# Generated by Django 3.2.9 on 2022-04-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0026_auto_20220405_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videos_thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='videos thumbnail'),
        ),
    ]
